### ISSUE TITLE
Whats left?

### ISSUE THREAD

**Issue by keabro** [CourseReps/ECEN489-Spring2016#3]
I looked through the commits and haven't seen anything changed so i'm checking in to see whats working.
**Chaance** have you gotten the IMU to display the correct data?
**Paul** how is the USB data transfer stuff merging with Fanchao's code does it work?
**Thomas** how did testing your send to server code with Fanchao's code go?
**Sam** I saw you uploaded some changes and it looks like you are good to go.
@ctg123 
@tbranyon 
@paulcrouther 
@samshore 
@Fanchao92

**Comment by Fanchao92** [comment]
I have a question here. where should we 'new' a DBAccess object? In the
pushtodb() function? Or in the main fragment and we pass it to pushtodb()
as an argument? Because the button for data transmission is in the main
fragment, so maybe the new thread for the data transmission is initiated in
the main fragment, and it also needs the access to the database.  If the
database is opened in the main fragment, we may need to create only one
object for the database. And do we need to do the synchronization by
ourselves? Or SQLite will do that for us? Because pushtodb() is writing to
the database, and data transmission is reading. If we need to do
synchronization by ourselves, then I think it's better for us to initialize
the database in the main fragment, and use the sync mechanism provided by
Java for the two operations, like "synchronized(dbObject)" or something
else.

2016年2月29日星期一，Keaton Brown <notifications@github.com> 写道：

**Comment by Fanchao92** [comment]
Or that's why we should put pushtodb() along with data transmission, so we
code the data transmission to take place after pushing to database, and we
don't bother ourselves with the synchronization?

2016年2月29日星期一，Fanchao Zhou <fanchaozhou1992@gmail.com> 写道：

**Comment by tbranyon** [comment]
I'm unsure about the synchronization, but it sounds like the DBAccess object should be created in the main fragment and passed to pushtodb(). That way both local writes and transmissions to the server will have access. Those 2 processes need to be separate, so that data points can be recorded outdoors and then later when the user brings the device inside and has wifi access, they can then push the data to the server.

**Comment by Fanchao92** [comment]
So should we push data to database when we are collecting them, and we have
another button for data transmission? If so, then I think the code in
'Core3' folder should fit.

2016年2月29日星期一，Thomas Branyon <notifications@github.com> 写道：

**Comment by keabro** [comment]
Ok so i'm going to change pushtodb() and pulldata() to accept arguments.
pulldata(String transferID, int RSSI, String transferID, Float[] imu);
pushtodb(String transferID, int RSSI, String transferID, Float[] imu, *DBaccess*); 
If Fanchao is passing me the DBaccess object how do I define that in the arguments?

**Comment by Fanchao92** [comment]
Do you really need to modify pulldata? I just pass the database object to
you for you to push data, I think

2016年2月29日星期一，Keaton Brown <notifications@github.com> 写道：

**Comment by keabro** [comment]
I have to modify pulldata in order to receive the usb data. since paul has to interface with you you have to pass me the information he is sending us.

**Comment by Fanchao92** [comment]
OK, I will discuss with Paul about how his part is integrated into the
framework, and then maybe we can figure out whether I'll need to pull his
data in the main thread and pass the data to you, or we can put his part
into your pulldata() function. He showed me his part last Friday, and it
seemed we needed to add another button to the action bar.

**Comment by samshore** [comment]
Yeah I made the DBAccess class thinking it would just be used in the main fragment. Like what I had in mind was there would be like a collect data button or something and then when that was pressed just get the data from Paul and chance and then save it to the database. I don't know if a separate class would be necessary. But I'm not sure, I guess it doesn't really matter.

**Comment by keabro** [comment]
we can move all my stuff into the main activity.
