### ISSUE TITLE
Project report

### ISSUE THREAD

**Issue by keabro** [CourseReps/ECEN489-Spring2016#4]
I have created a PROJECT.md file under Project1 in the repository. We can each make changes to the project file and when we are done we will take that and copy and paste it to the wiki. I have created a layout with sections so each of you can write your separate pieces in.

As of today Fanchao, Sam and I got the app to work without errors, but with dummy data until all the pieces have been finished. If we can get the pieces that aren't finished done by the end of Tuesday then we have time Wednesday to make everything work together correctly.

**Comment by paulcrouther** [comment]
I've got the serial port working. Need some help with integrating the code in the app to listen to RX XBee.

**Comment by Fanchao92** [comment]
Do you need another thread to keep checking all the time if RX Xbee
has data? Or you press the button for data collection and check if there's
data. If yes, you pull the data, otherwise you return a null string?

2016年3月1日星期二，paulcrouther <notifications@github.com> 写道：

**Comment by paulcrouther** [comment]
I believe we're trying to just pull data when the button is pressed. We
need to update on button_refresh?

**Comment by Fanchao92** [comment]
Yeah, we just pull data when the user presses the button. I guess we need
to update onCreateView method in MainFragment.java file. In that method,
there is a handler for the 'refresh' button. But I am not sure if we need
another thread or AsyncTask, because we are reading from an external
device, which is supposed to be relatively "slow".

2016年3月1日星期二，paulcrouther <notifications@github.com> 写道：

**Comment by Fanchao92** [comment]
Maybe we can go with no new threads first, and see if it's good?

**Comment by paulcrouther** [comment]
I'm opting for no threads right now. I don't think we will need them yet.
